### ISSUE TITLE
Allow people to specify pronouns when people sign up

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#229]
Link to resources elsewhere to explain it.  Doug May has volunteered to find such a link

**Comment by lilliealbert** [comment]
This seems like a good example of a thing that we should be pushing organizers to include in their events, but just adding a field to RSVP + some links about why pronouns are important is not enough.

It's come up that organizers sometimes don't notice that people had signed up for childcare (we're now emailing them every time this happens, and they can not offer childcare if needed), and I worry sometimes that if we don't have the right UX around the questions we ask in RSVPs and the way we present those things to organizers, that people signing up will think that the organizers are sensitive to their needs (be they gluten-free food, childcare, or pronouns) and the organizers will not actually be planning on doing anything to better accommodate those people. (I'd like to see Bridge Troll be more configurable with things like food options, since there will be workshops that use the software in places where finding gluten free options isn't realistic for the organizers.)

Since many organizers don't print name tags (one of the more common places to put pronouns), having that information stored in the app doesn't seem like it would do a lot.

I think volunteer + organizer education around this would be much more effective, such as: 

* Encouraging volunteers to lead classroom introductions including stating one's pronouns
* Telling organizers to have people include pronouns on their name tags
* Including a brief explanation of why stating pronouns explicitly is important in the opening presentation

**Comment by lilliealbert** [comment]
I'm going to close this issue, but I think that doing more education with volunteers, organizers, and attendees would be a good thing for RailsBridge (and any *Bridge) to do.
