### ISSUE TITLE
Add ability to send email to Organizers group

### ISSUE THREAD

**Issue by glenna** [railsbridge/bridge_troll#282]
Currently the options are
* All Attendees
* Only Students
* Only Volunteers

Unfortunately "Volunteers" do not include the Organizers.

**Comment by lilliealbert** [comment]
I don't think organizers should be a separate group mailing option on Bridge Troll, but I do think that giving organizers a way to include their co-organizers on emails makes sense.

I see two options: 

**Add a "CC all organizers" checkbox to the email page**
This would allow organizing teams that have decided to divide & conquer with just one person taking the lead on attendee communication not to destroy the inboxes of their fellow organizers except on purpose. This is another checkbox, so another decision point for already-harried organizers, so that's not super great.

**BCC all organizers on all sent emails**
Prevents co-organizers getting all the replies to mass emails sent, and as a default would avoid making organizers make yet another decision. But I do also have the secret fear that organizers will get emails and be confused and think that somehow Bridge Troll thinks that they are RSVPd as students or volunteers :neutral_face: 

@glenna @tjgrathwell @eliduke @rachelmyers — what do y'all think?

:love_letter: :love_letter: :love_letter:

**Comment by clararaubertas** [comment]
as an organizer, I would like the first option (optional CC organizers) to be available!

**Comment by lilliealbert** [comment]
@raebot added this functionality in 29340edc7335c921d8a9ff6a829a58fe0c3617b2

:tada: :tada: :tada:
