### ISSUE TITLE
Attendees Are Not Receiving Emails from Organizer

### ISSUE THREAD

**Issue by LauraKirby** [railsbridge/bridge_troll#284]
While the "Email Attendees" page says that I have emailed all attendees, there are people who emailed me stating there friends received emails that they did not. Likewise, I did not receive the copy of the email sent in my inbox.

**Comment by lilliealbert** [comment]
It seems like a this is a deliverability issue with our mail provider — is there anything we can do here? We could add text to the bottom of all the emails that says "Add troll@bridgetroll.org to your contacts to always get updates!" but that is something I have never done in my whole life, despite the number of emailing orgs that have asked for it.

**Comment by rachelmyers** [comment]
@rothsa, Could you give us some pointers for keeping the Bridge Troll emails to attendees from being marked as spammy?? :grimacing:

**Comment by marclove** [comment]
This is happening because SPF and DKIM haven't been setup or there's something wrong with their configuration. It looks like bridgetroll uses SendGrid. Here's their documentation for setting it up.
https://sendgrid.com/docs/Glossary/spf.html
https://sendgrid.com/docs/Apps/dkim.html

It'll have to be done by someone who has both admin rights on SendGrid and access to the DNS records of bridgetroll.org. I'm happy to help out in any other way that I can.

**Comment by tjgrathwell** [comment]
@marclove Bridge Troll is using the Bronze-tier SendGrid plan on Heroku, which as far as I can tell should be setting the SPF and DKIM correctly, because the email is still technically coming from `sendgrid.me`. From the docs, it seems like you only need to do something special if you're using a higher tier than that (and have your MX records set up, etc).

SendGrid's dashboard claims we've had <20 bounces/blocks in the last month, but I don't know how that relates to whether a user is finding Bridge Troll emails in their Spam folder.

**Comment by marclove** [comment]
@tjgrathwell In order to set up DKIM or SPF, you have to add a few DNS records to bridgetroll.org. SendGrid and Heroku have no ability to change bridgetroll.org's DNS records, so there's no way that it could automatically take care of it.

Here's the DNS records for bridgetroll.org: http://viewdns.info/dnsrecord/?domain=bridgetroll.org. If SPF and DKIM were set up, there'd be TXT records pointing to SendGrid. Here's an example of a domain that has SPF & DKIM set up: http://viewdns.info/dnsrecord/?domain=goodeggs.com. The instructions on how to set up those DNS records is in the SendGrid docs I linked to earlier.

Emails automatically filtered to a user's spam folder most likely won't show up as bounces or blocks. I'm pretty sure most email services only report an email as blocked if a user explicitly reports it as spam.

**Comment by tjgrathwell** [comment]
@marclove / all, per most of the Sendgrid docs I can find, those DNS changes won't matter unless we're on a higher tier of Sendgrid service, because all the mails are validating their DKIM/SPF using the `sendgrid.me` domain.

References: 
https://sendgrid.com/docs/Apps/dkim.html
https://sendgrid.com/docs/Glossary/spf.html
https://community.sendgrid.com/sendgrid/topics/why_dont_i_need_an_spf_record_or_other_dns_mods

I set up the SPF TXT record on bridgetroll.org just now for fun, but I don't think it's going to make a difference as long as gmail is trying to validate using `sendgrid.me`.

Here's the headers I see on a recent mail:
```
Delivered-To: tjgrathwell@gmail.com
Received: by 10.28.130.148 with SMTP id e142csp548803wmd;
        Tue, 21 Apr 2015 06:19:45 -0700 (PDT)
X-Received: by 10.182.63.3 with SMTP id c3mr18586645obs.1.1429622383877;
        Tue, 21 Apr 2015 06:19:43 -0700 (PDT)
Return-Path: <bounces+627457-e8a3-tjgrathwell=gmail.com@sendgrid.me>
Received: from o10.shared.sendgrid.net (o10.shared.sendgrid.net. [173.193.132.135])
        by mx.google.com with ESMTPS id w206si1343639oib.41.2015.04.21.06.19.42
        for <tjgrathwell@gmail.com>
        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 21 Apr 2015 06:19:43 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+627457-e8a3-tjgrathwell=gmail.com@sendgrid.me designates 173.193.132.135 as permitted sender) client-ip=173.193.132.135;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of bounces+627457-e8a3-tjgrathwell=gmail.com@sendgrid.me designates 173.193.132.135 as permitted sender) smtp.mail=bounces+627457-e8a3-tjgrathwell=gmail.com@sendgrid.me;
       dkim=pass header.i=@sendgrid.me
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=sendgrid.me; 
	h=from:to:subject:mime-version:content-type:content-transfer-encoding:x-feedback-id; 
	s=smtpapi; bh=YgTt9t3UmvlrCtrWNQhbFEmGSjM=; b=xbhRW3k0MxQ+NpIFdP
	k7CmRzCbGVoh4owkmlZs5Bl4bgGm3scZbJHMANyCO+7VH3/UVSBMFjO74V9NHxRb
	wB3djjpLbz4XNdZqBi3kIWL56uclFoFKE8NeCsD4yQjVkmAHA/DACLHUibUKlPpK
	AszHhrpCNMxj2mspVYkdH1iQA=
Received: by filter0181p1mdw1.sendgrid.net with SMTP id filter0181p1mdw1.11984.55364E6BD
        2015-04-21 13:19:39.805610437 +0000 UTC
Received: from heroku.com (ec2-54-162-169-50.compute-1.amazonaws.com [54.162.169.50])
	by ismtpd-038 (SG) with ESMTP id 14cdc225548.135a.30b7b4
	for <info@bridgetroll.org>; Tue, 21 Apr 2015 13:19:39 +0000 (UTC)
```

The SPF and DKIM look like a 'pass' to me.

* Is it possible that it would fail for other users? Gmail users, yahoo mail users...?
* Do we need the `bridgetroll.org` whitelabeling to get better deliverability? The step up from "Bronze" to "Silver" on Sendgrid is $70/mo.
* How bad is our deliverability, really? How would we know if people aren't getting emails? If an email is delivered to a forest, does it make a sound?

**Comment by rothsa** [comment]
Have you guys brought this up with SendGrid support yet? Your validation looks fine, it's possible that you are on an IP that is not ideal for your volume and mail quality. If you're low volume, for example, you should probably not be on your own IP.

The most useful thing you can possibly do is contact the postmaster/ISP that handles the mail for one of the places you are not getting mail through to and get headers from that location - from there you can deduce whether it's a systemic issue or just a single time thing. 

I'll forward this over to Derek Baines at SendGrid, he'll know who your account manager is and how to deal with this.

**Comment by lilliealbert** [comment]
Is there anything else that needs to happen here? Has anyone else heard of people not getting emails from Bridge Troll?

Can we close this issue and open another one if it comes up again?

**Comment by lilliealbert** [comment]
Closing this for now. If it comes up again, we can reinvestigate.

:bear: :palm_tree: :cat:
