### ISSUE TITLE
Rename "Chapters" to "Regions"

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#323]
The RailsBridge board would like to move toward a system where there are Official Chapters that have bank accounts / PEX cards / seats on an advisory board, while also supporting places where workshops happen without that infrastructure. So we'd like to have "City" mean any place that has a RailsBridge workshop, and "Chapter" mean a place that has workshops regularly and meets criteria for having PEX cards and such.

"Chapter" is also not ideal for places where multiple *Bridges co-exist. We'd like to encourage *Bridges to share resources like venues, and having a separate *Bridge chapter per city would make that really hard.

So: let's rename "Chapters" to "Cities" throughout the whole app.

**Comment by tjgrathwell** [comment]
I think there are a lot of difficulties involved here.

A "chapter" kinda means at least two different things:
* A geographic area, like NYC or the "SF Peninsula"
* A group of people involved in organizing workshops, like the SF RailsBridge or MobileBridge teams

Of the existing chapters (https://www.bridgetroll.org/chapters/) I don't think the following correspond well to "cities":
* Boulder/Denver
* Hawaii
* Kentucky
* SF Peninsula
* Raleigh/Durham/Chapel Hill

...so at the very least, the geographic distinction might work better as "region".

In Bridge Troll, events belong to locations (which belong to chapters) and users can sign up for email alerts when a new event happens in that chapter.

There is an additional user role, a "Chapter Leader", which is bestowed on the creator of a chapter and whomever else that creator chooses. Chapter Leaders can edit special location metadata (like venue contact info) and edit the chapter name.

If we were going to rename "Chapters" in the app, we need to figure out what to do with the "Chapter Leader" role. It's possible we just leave it as-is but with a name like "Regional Manager", assuming we're okay allowing multiple sub-organizations in the same geographic area (mainly just SF RailsBridge and SF MobileBridge, currently) to share venue info. In that case, I don't know if Bridge Troll needs to know anything else about the local political structures, but my ideas on this are only partly baked.

**Comment by siruguri** [comment]
It sounds like the idea is to have "Chapter" be the entity that has accountability, while City represents a geographically contiguous area to which students/volunteers hold some affiliation. The natural hierarchy here would be that a chapter is responsible for an exclusive list of Cities, with the decision of how to financially manage (budget) the cities being left to the chapters.

My 2c is that this is less an app issue and more an organizational issue - can a City ask to be in more than one Chapter? Can it ask for funds from more than one chapter? Or do funds always come from a single entity, rather than flow through the Chapters?

If the goal is to solve the organizational problem, the app could be left as-is, and the accountability entity be called something else, like Regional Governance Committee.

**Comment by sarahmei** [comment]
Totally agree that chapter is the wrong word here - we need to start distinguishing between places that do one-off or occasional events, and places that do regular scheduled workshops & have a team of folks.

I don't think we're anticipating a hierarchical arrangement in which a set of cities falls under a chapter. Instead, every place we have workshops is a city, and some cities are also chapters. The places where events are one-offs and perhaps there is no stable leadership - just cities. Cities that are organized, have repeating events, and stable leadership - they graduate into a chapter.

Most of what we currently call chapters are cities anyway, and we could make the ones that aren't into cities. "Silicon Valley" and "Research Triangle" are reasonable city names, despite not actually existing. Pretty sure Kentucky has a city somewhere... And "Denver metro" seems reasonable for Boulder/Denver although that one's probably fine as-is.

We will have both chapters and cities at different granularities - some chapters will serve a narrow area, and some cities will cover huge metro areas. The difference is their level of organization. As to how one moves between the groups, our current thinking is that cities could apply to become chapters. Once they're approved they get a bank account & debit card. We haven't totally nailed down that process yet, so input welcome on that.

Terminology-wise, the other option I see besides Cities is "Locations", but I think that's already used for workshop locations (i.e. companies where we host events). The term itself is vague enough that I think it would be confusing.

**Comment by ultrasaurus** [comment]
How about the word "region" ?  The other thing that would make that a good change is that we're starting to have both RailsBridge and ClojureBridge "chapters" in one region, and San Francisco also has MobileBridge.  People want to see what is near them regardless of technology.

**Comment by kmolo** [comment]
As @siruguri asked, does this definition process have to happen inside the Bridge Troll application?  

It seems like the flexibility of 'Chapters' works well for the application.  Perhaps the new structures should take place on the website & in the 'organizing' repo README.

It's convenient to have a single regional 'Chapter' as new *Bridges start using Bridge Troll:
 - users don't have to manage multiple subscriptions
 - users get to hear about new *Bridges
 - new *Bridges don't have to get into whether to auto-subscribe those who follow other events in the same region

**Comment by lilliealbert** [comment]
@kmolo I think having consistent words between the organizational structure and Bridge Troll is important, and I actually think chapters is more limiting/confusing for cities where chapters coexist and share resources.

I think all the plusses you said about regional chapters could be said about regions. It would basically be a drop-in rename, with the same current behavior, but with less questions about whether someone should join MobileBridge SF, RailsBridge SF, or both.

At this point I don't really care if it's "region" or "city", even though the "region of SF" and the "region of the East Bay" sound weird to me, we're probably an odd case.

**Comment by kmolo** [comment]
I too like the word "Region" over "City" -- works better for Boulder/Denver, Hawaii, and Kentucky -- and "SF Region" and "East Bay Region" seem to work well enough if you have the word "Region" follow the placename.

Then "Chapter" could be re-purposed to the uses you are discussing.

**Comment by carlisia** [comment]
I will regret if my questions end up being useful only to me, but perhaps it can add some additional insights.

I'm in the system as a regular user, and this is good because it allows me to see what GoBridge students and volunteers will see. This discussion has triggered a couple questions for me:

1) @tjgrathwell said at the very beginning: `In Bridge Troll, events belong to locations (which belong to chapters) and users can sign up for email alerts when a new event happens in that chapter.`

I don't see that. Where can I sign up for email alerts for the chapter(s) I belong to? (I looked everywhere :) )

Of course, for chapters/regions with heavy course load (SF as an example) I can see ppl not using this feature unless they could filter it by the Bridge(s) they are interested in.

2) If there is the concept of a chapter lead, where on Bridge Troll can I see who is the lead for my chapter(s)? I also looked for that and cannot find it. 

I could see how it would be useful for say, companies wanting to offer office space or otherwise anyone wanting to get in touch with a local chapter lead to get their help with admin things.

And again, it would be useful to have it categorized by Bridge.

My interest here is to scale the work as much as possible by having regions be more self-sufficient, rather than having the default contact me personally to get things going since I could be a bottleneck.

3) @tjgrathwell also says: `There is an additional user role, a "Chapter Leader", which is bestowed on the creator of a chapter and whomever else that creator chooses`

If we are talking about having chapter leads be people with PEX cards and other responsibility, should we not have a system where the admins are vetting this a bit more? I'm saying this as a newcomer and not knowing much about how the system works in practice.

**Comment by tjgrathwell** [comment]
Hey @carlisia, sorry for not replying to this sooner!

I'm just finishing up the rename of Chapter -> Region, so the language here is changing / will change / has changed.

1. The email alerts toggling functionality should be on your "Settings" page, accessible in the upper-right when logged in:

  ![screen shot 2015-11-26 at 10 15 15 pm](https://cloud.githubusercontent.com/assets/1041691/11434017/50614278-948b-11e5-8447-01e56922091a.png)

  ![screen shot 2015-11-26 at 10 15 33 pm](https://cloud.githubusercontent.com/assets/1041691/11434021/54b3521c-948b-11e5-90fe-23c9227708e4.png)

  Additionally, when RSVPing to an event, you can opt in to / out of emails for that event's chapter:

  ![screen shot 2015-11-26 at 10 17 56 pm](https://cloud.githubusercontent.com/assets/1041691/11434036/98c2f994-948b-11e5-9a03-6e558c3c3473.png)

2. Chapter leaderships are currently only exposed to site admins (a small handful of people) and existing chapter leaders. When available, they show at the top of Chapter's page (e.g. https://www.bridgetroll.org/chapters/3), like this

  ![screen shot 2015-11-26 at 10 20 42 pm](https://cloud.githubusercontent.com/assets/1041691/11434067/0bd8a226-948c-11e5-80a0-7e90b0bf8a2d.png)

  We may want to expose this information more publicly, but there's always a balance between providing information to helpful parties vs. accidentally getting people spammed.

3. The Chapter Leadership elements in Bridge Troll aren't very fleshed out yet, but so far they have no connection to anything financial. So far, the system is trying to make it easy for someone to post their event without having to ask anyone permission, though the lengths we go to achieve that goal might be questionable.

  Every event needs to be read over by a site admin before it will show up on the site, anyway.

**Comment by ultrasaurus** [comment]
Thanks @tjgrathwell -- this long-awaited feature should be *very* helpful.

@carlisia to provide a little background, in SF we find a lot of people like learning different tech.  For example, a lot of the Rails engineers are also mobile developers (or want to learn iOS or Android) and I heard lots of positive feedback when people in SF started receiving MobileBridge event notifications.  I expect that there are a lot of people from the other Bridges who are interested in learning Go as well.

**Comment by carlisia** [comment]
@tjgrathwell no worries and thank you for the explanations. Now I see the email signup functionality re: per regions, it's all clear to me.

@ultrasaurus to be sure, I agree that it's very useful to be able to be notified of new courses in a region. But I was thinking about giving everyone the option to opt-in to the tech notifications they want. I could think that Go developers will want to also get notified about Rails and mobile development, but I can safely assume that some won't. The only question to be answered is, what percentage of the users will turn off the very useful email notification all together to avoid getting emails they don't want. Many SF Rails developers are voicing that they are glad to get notifications for other tech, but what percentage of the user base do they make out, and are the ones not speaking up also just as glad? I realize you probably have a very good idea though, but as new Bridges, new regions, and different types of people start to join, some numbers might be useful.

I'm saying this to better explain my reasoning and suggest that maybe it's something worth keeping an eye on; it's not a problem for me atm.
