### ISSUE TITLE
Event time zone should be inferred from location

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#390]
no reason to make people define time zone if the location is already at a specific lat/long that obviously could be associated with a tz

[Originally written by @tjgrathwell, imported to GitHub on 11/21/15]

**Comment by StevenXL** [comment]
@lilliealbert I'm working on this particular issue. I wanted to let you know how I'm proceeding with this because it seems to be a substantial change in logic / design.

Getting the `Location` model to understand its own timezone based on its coordinates was simple enough, using  a gem called `nearest_time_zone`. I chose this gem because it does not need to make any external API calls. 

The `Event` model, because it belongs to a location, can simply ask the location for the time zone. 

This design choice means that I will have to add a validation, and not simply an association, that requires that each `Event` instance is associated with a `Location` instance. This will change some of the tests - for example, we will no longer test that `Event` is invalid without a time_zone, since we will test that it is invalid without a location, and the location test suite will test for time_zone. 

There are a few other changes that stem from this, but as long as you agree that an event must have a location, I think the rest will logically flow from that.

**Comment by ultrasaurus** [comment]
hi @StevenXL -- thanks for pitching in and posting your logic!  As a user of Bridge Troll, I think I might sometimes want to save a draft event without a location.  One thing to consider would be to have a timezone for a chapter.

**Comment by aneyzberg** [comment]
hey @StevenXL -- just wanted to check in and see if you are still working on this issue? If not, let us know. Someone else may be able to pick this up :)

**Comment by StevenXL** [comment]
@aneyzberg My apologies. I have lost track of where I am in terms of this particular issue. (Recently started my software development career :+1: ). I will check on how much work I have completed on this and get back to you whether I will be able to finish it or not in the next 24 hours.

**Comment by aneyzberg** [comment]
@StevenXL Sounds good, thank you :) and congratulations on the new software development job!

**Comment by StevenXL** [comment]
@aneyzberg Thank you very much - and my sincere apologies for the delay in replying. Unfortunately, I don't have the time at the moment to contribute to this project, and I don't want to block someone else from doing so. As a result, I will not be completing this issue. Thank you @aneyzberg for reminding me I had this outstanding.

**Comment by lilliealbert** [comment]
Closed with 435cc5191420ad42d40a71f9c4ec008cdd41d11b
