### ISSUE TITLE
de-RailsBridge all the things

### ISSUE THREAD

**Issue by carlisia** [railsbridge/bridge_troll#398]
1) Link to cookbook
When creating an event, there is a link to the cookbook that goes to the RailsBridge repo. A lot of the info doesn't apply to GoBridge workshops (for example, 90% of the installfest). 

2) Link to task list
When creating an event, there is a link to a task list in the RB repo, and that list has links that point to the other RB repos and mailing-list.

3) Email messages
I created my first BT event (in draft) to and was a bit taken aback when I looked at my mailbox and there was an email from RailsBridge. When I looked I knew what it was (a message informing that I had signed up.)

A lot of people in the Go community don't know of RailsBridge. For them and even for others who do, this message could be overlooked/dismissed as not relevant, when in fact it contains important information.

Is there something we can do about it? Maybe use Bridge Troll branding instead of RailsBridge?

![image](https://cloud.githubusercontent.com/assets/16508/11326821/8f02ade8-9128-11e5-8f29-51923b7b07b6.png)

---
**Suggestion(s)**

Perhaps one way to resolve differences is for each Bridge to have its own `workshops` repo (with the issue workflow as per @rachelmyers invention, list of courses (see how I do that: https://github.com/gobridge/workshops/) and task list with specific info for that Bridge), and everything related to organizing goes into an updated/reorganized `cookbook` repo under BF

Maybe we could allow people to select a Bridge before getting started with creating an event, and then pre-polulate those items according to the chosen Bridge? Issue https://github.com/railsbridge/bridge_troll/issues/397 could also be addressed by a system like this.

**Comment by lilliealbert** [comment]
We are definitely interested in de-RailsBridge-ing the various part of Bridge Troll, and it's something that @kmolo has been really helpful in pointing out through her work with MobileBridge.

It would be helpful if we could collect all of the places in the app that are RailsBridge specific.

I can change the link to the cookbook on the organizer console and the event form to the generic one now: https://github.com/bridgefoundry/WorkshopCookbook/wiki/Cookbook, since it does already exist.

(I'm not sure I understand your last suggestion, but I'd love to talk about it when we have a call about documentation. Right now, I'm waiting on who will be attending from ClojureBridge, and then I'll send out a Doodle to schedule.)

**Comment by lilliealbert** [comment]
lol, both of us updating the title -- I like yours better :smile:

**Comment by carlisia** [comment]
LOL - I updated the body to reflect your suggestions. Feel free to edit it some more!

**Comment by lilliealbert** [comment]
Alright, I did a global search of the codebase for `railsbridge` and did a lot of copy editing: 7d060a12f619533d7614cabc5e7c4d0da5cac46a

Closing this issue for now, but if you find other things, definitely open a new one!

:grinning:

**Comment by carlisia** [comment]
:clap:
