### ISSUE TITLE
Allow volunteers to be added to unpublished events

### ISSUE THREAD

**Issue by carlisia** [railsbridge/bridge_troll#400]
Sometimes settling on a event date is very dependent on having enough volunteers for the event. It would be very handy to allow people to add themselves as volunteers to an event before it is published, so organizers could monitor how many volunteers they have at any given time.

**Comment by lilliealbert** [comment]
I think it could be strange to share an event privately and gather RSVPs and then change the date, since you wouldn't know which volunteers could only make the original listed date. Date-deciding seems like something that might be better hashed out over a mailing list of volunteers than within the app.

Currently, pending-approval events can be RSVP'd to by students or volunteers. So if you shared the link to your pending-approval event with a group of volunteers, they would be able to RSVP to the event without it being listed on the Bridge Troll homepage. This is sort of a happy accident of how approval got coded — it wasn't really an intentional feature.

The problem with this system is that organizers don't have the ability to control when an event goes from pending-approval to approved, and until we have the ability to have different Bridges / chapters approving their own events, I'd be loathe to recommend this option too much. (Since it involves emailing me, and then I have to communicate with the other approvers about not approving the event, then you have to tell me when you want the event approved, which not something I'd want to be doing for every single workshop.)

We could add an additional "secret" status, where an event isn't visible on the Bridge Troll home page but is otherwise published. (Although generally, picking sensible defaults so that beginner users of Bridge Troll aren't overwhelmed by options is something I'd like to do, and adding an additional state definitely add complexity to the publishing process that I'm not sure is worth it.)

**Comment by carlisia** [comment]
@lilliealbert what you said makes complete sense: volunteers availability will change based on date (duh) so what I proposed is not feasible. Like you said, best to hash it out elsewhere. 

I am ready to close this issue if you are. 

One question though. You said `...then you have to tell me when you want the event approved``` I thought to do that I would only have to press the `Submit Event for Approval` button. I'm sure I'm missing some nuance. :)

**Comment by carlisia** [comment]
...aaaand the answer is right there: `pending-approval events can be RSVP'd to by students or volunteers`. It's the `pending-approval`, not the `draft` state that allows for the RSVPing to happen. Gotcha.

**Comment by lilliealbert** [comment]
Yeah, it's pretty subtle and confusing!! :stuck_out_tongue_closed_eyes:
