### ISSUE TITLE
Update test methodology to not count emails

### ISSUE THREAD

**Issue by sidhene** [railsbridge/bridge_troll#457]
Currently a number of the automated tests rely on email count to verify whether an action has been taken or not. This blocks the possibility of features that use email communications to improve user experience (examples: alerting organizers to approval, letting new organizers know about the organizer console, which they sometimes miss) when doing so would change the email count and invalidate the tests.

This story covers developing a new methodology for the tests, other than email count, and updating the tests. Commenters can help by identifying which tests would be affected.

**Comment by tjgrathwell** [comment]
This sounds like technical work that should be a part of whatever story needs to change that functionality. Are you working on a story/issue in this area?

There are already quite a lot of issues stacking up on this repo, I'd prefer the issues list be focused on things that add end-user value rather than technical chores.
