### ISSUE TITLE
Add "ElmBridge San Francisco" chapter

### ISSUE THREAD

**Issue by avh4** [railsbridge/bridge_troll#482]
Hello, we're organizing the first ElmBridge San Francisco for Oct 22nd, and would like to use bridge troll.

Can we get `ElmBridge San Francisco` added as a chapter?

**Comment by tjgrathwell** [comment]
Okay, the chapter is there now!

Since this is a new curricula, you'll probably want to add a description and experience level breakdown to [course.rb](https://github.com/railsbridge/bridge_troll/blob/bc76a523a4d24ad3aae54f154d6f0b15e72a707e/app/models/course.rb), something like https://github.com/railsbridge/bridge_troll/commit/3a95d6bdebb80942ab7e6d3024daca666fadc776 for example
