### ISSUE TITLE
Survey link in email is broken

### ISSUE THREAD

**Issue by Anasauce** [railsbridge/bridge_troll#503]
An email that is sent our to RailsBridge SF attendees contains link to a survey that appears to be broken. This was the link that I received:

https://www.bridgetroll.org/events/321/rsvps/17661/surveys/new

If anymore info is needed feel free to contact me

**Comment by lilliealbert** [comment]
Hmm. It seems like it's an inconsistent issue, since there are responses showing up: https://www.bridgetroll.org/events/321/surveys.

Where did that specific link come from? From the email you personally received about the event?

**Comment by tjgrathwell** [comment]
Is it possible you tried to take the survey while logged into a different Bridge Troll account? 

Right now the only way I know of where following link would produce an error is if you are logged in as someone who didn't attend the workshop. Since you got the email, you definitely attended in some capacity, but maybe the computer you followed the link on was logged in to someone else's account?

For now, I've changed the error message that shows up, which used to be 
![screen shot 2016-10-25 at 11 46 24 pm](https://cloud.githubusercontent.com/assets/1041691/19715955/b8c06e96-9b0d-11e6-9675-29b308e35851.png)
to now be
![screen shot 2016-10-25 at 11 47 31 pm](https://cloud.githubusercontent.com/assets/1041691/19715957/bfca3c1c-9b0d-11e6-9260-310d2c4e7988.png)

i welcome any alternative explanations!! ❓ 😕 ❓
