### ISSUE TITLE
Organize Chapters Dropdown on External Events page

### ISSUE THREAD

**Issue by mfjenn** [railsbridge/bridge_troll#505]
https://www.bridgetroll.org/external_events/new The organization of the Chapters doesn't seem to make sense on the dropdown. Could it either be populated by Bridge, then specific chapter, or at least organized alphabetically? It is really hard to find a chapter. To make this tool scalable, it seems like it needs to be more organized.

**Comment by lilliealbert** [comment]
@mfjenn You can start typing the name of the chapter/city and it will filter by what you type in. Since there are so many, I would suggest doing that to save time.

Since this tool is one that we'll hopefully be using less and less as orgs start using Bridge Troll, I'd like to not put too much time into it since there are so many other things in the app that are a higher priority.
