### ISSUE TITLE
we need to be able to delete external events

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#511]
There are a few duplicate events that I've noticed as I'm entering missing data, in order to pull together summary statistics.  

It looks like it is supported in the controller:
https://github.com/railsbridge/bridge_troll/blob/master/app/controllers/external_events_controller.rb

but not in the form:
https://github.com/railsbridge/bridge_troll/blob/master/app/views/external_events/_form.html.erb

If I'm reading the code right, then I think anyone who has permissions to edit may also delete, even though there isn't UI for that.  I wonder if we should consider limiting who can delete (since I fear losing history!) or have a soft-delete (where we add a field to the model that something has been deleted and just not show it -- safer, but adds complexity to the app)

cc @LauraKirby who has been helping me this weekend, and might help with coding too :)

**Comment by tjgrathwell** [comment]
It seems like somebody added External Events for a lot of the events that were already in the DB as imported meetup events.

Can we just remove these from the DB manually? I'm worried that if it was this easy to create a bunch of duplicates by mistake, deleting them might make it easy to make mistakes as well.

**Comment by ultrasaurus** [comment]
Deleting anything manually seems a bit scary.....  Seeing your note on the mailing list, if the meetup URLs are still in the database, then maybe we could write a script to de-dup (and then write a rule which prevents that particular error from happening again, though maybe it won't once we get our history recorded)

**Comment by lilliealbert** [comment]
If we know the events we need to remove, it seems like doing it via a UI or via a Rails console is about the same level of risk — but building a UI seems to take more work.

Since we're in the process of backfilling old events and more people have access to create external events than have previously, I think we're probably going to have some temporary pain that will taper off once the backfill is done. And getting more Bridges using Bridge Troll directly will also cut down on potential dupes via the external events feature (since we'll just have to use it less in general).

Given that, I'd rather do the smallest thing possible (fixing them in the DB) and then see if there's a need to be able to delete external events via the UI in the future.

**Comment by tjgrathwell** [comment]
Hey good news, there was a delete button all along, it's on the index page:

![screen shot 2016-11-27 at 9 51 35 pm](https://cloud.githubusercontent.com/assets/1041691/20658242/441b640e-b4f0-11e6-8fb8-907dd4179621.png)

I've deleted the duplicate events.

I'm going to close this and follow up on the situation in email.

**Comment by ultrasaurus** [comment]
oh, goodness.  I can't believe I missed that.  thank you!
