### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by webRat** [railsbridge/bridge_troll#530]
I'm unable to login without using the "Forgot Password" workaround.

Browser: Chrome Version 56.0.2924.87 (64-bit)
OS: macOS 10.12.3

How to repeat:
* Clear cookies
* Go to site, and attempt to sign in
* Watch as nothing seems to work

Workaround:
* Instead of attempting to sign in, use the "Forgot Password" route
* Wait for email
* Click link in email
* Use existing password instead of creating a new one
* When you're done, note that you're logged in.

**Comment by steveklebanoff** [comment]
after confirming my registration, i'm unable to sign in as well

**Comment by tjgrathwell** [comment]
@webRat Yikes, that's really bad. Seems like it's probably been broken since [the Rails 5 upgrade push on Feb 28](https://github.com/railsbridge/bridge_troll/commit/542dc1566ebe0eb29576d1dd0a60665d49256765), surprised it took this long for anyone to report it.

OAuth signin seems unaffected, so maybe people most people have been using that.

I've reverted production back to the Rails 4.2 version for now, so password login should work for the moment. Looking into the long-term solution now.

**Comment by tjgrathwell** [comment]
Should be fixed now. FYI the issue was this thing documented in the Devise readme: https://github.com/plataformatec/devise/commit/c520e93733701321c86db320db181521caea0ca1. Didn't notice the positioning of `protect_from_forgery` was significant when I was looking over the changes from `rake rails:update`.

Thanks for reporting, please file another issue if you see any new weird things happen.

**Comment by webRat** [comment]
Thank you @tjgrathwell!
