### ISSUE TITLE
Please add a "ScalaBridge Silcion Valley" chapter

### ISSUE THREAD

**Issue by adelbertc** [railsbridge/bridge_troll#671]
Hello,

We are looking to start a Silicon Valley chapter of ScalaBridge and were instructed on the BridgeTroll website to create an issue to have it indexed.

Thanks!
-Adelbert

**Comment by nmcb** [comment]
I would suggest to call it the San Fransisco chapter.

(Sorry, Adelbert -- Huge admire of your work, and as far as I'm concerned you are worth every penny of your hourly rate: but looking at this globally, I think that the names of chapters should be named after capitals because of their global recognition).

**Comment by adelbertc** [comment]
@nmcb We purposefully did not call it San Francisco because San Francisco is a bit ways away from the South Bay where we plan on holding future events. From there our options sort of become limited to Bay Area, Silicon Valley, or South Bay. There is not a particular major city in the South Bay Area that can be considered representative.

I also think Silicon Valley has enough global recognition to be unambiguous in this case.

**Comment by xingyif** [comment]
Agree with @adelbertc SV is more recognized globally and it is unambiguous enough that we will be able to have ScalaBridge in both the south bay and SF under that name.

**Comment by nmcb** [comment]
I agree with the recognition, but in that case could argue that a The Netherlands chapter would be a good name for the current Amsterdam chapter, because even though Amsterdam has perhaps a better name recognition among programmers than the Netherlands, for varying reasons, it would claim a larger part of the globe in association with the goals of diversity and inclusion for the Scala community. 

Also, your name choice, a locally named region within a formal division of the country it is located in, and explicitly attached to the corporate diversion common within that country, would put the United States in a minority position with respect to the rest of the globe. Also, there are a couple of associations with the name Silicon Valley that could be offending to people from groups that are underrepresented in the tech industry.

As by example, the ScalaBridge chapter in the Netherlands started by two dudes that just met each other and live two villages away from each other. We called the chapter, Amsterdam, and needed to discuss with the sponsor why it wasn't named Amersfoort. That chapter will organise many, many bridges in the future, in Amsterdam, Utrecht, The Hague, Amersfoort, perhaps even Schin Op Geul for all I know. But it will always be organised a commute distance from Amsterdam. 

(And personally, as much as I like diversity of names within a community, I find the name to reflect something a bit too posh, for an organisation that is bootstrapping itself to be globally respected, and sorry for sharing personal opinion next to global argumentation).

But I won't be religious on it if you choose to prefer diversity over inclusion (in a agreement on how to name things). It's your good right, and I may be very well proven wrong in the future.

**Comment by GerretS** [comment]
As organizer of ScalaBridge Amsterdam, let me be clear here.

I had no specific preference whether our chapter chould be called 'Amsterdam' or 'The Netherlands'. @nmcb preferred Amsterdam and had some well-considered reasoning behind this so I decided to go with it without further decision as I had no clear preference.

I feel all ScalaBridge chapters are connected through two things that *really* matter. The Goal as written on the frontpage of the site, "Building an inclusive Scala community with introductory programming workshops for underrepresented groups. " which is what we do, and the ScalaBridge Code of Conduct.

Everything else follows from there, and the further you get into details, the less important it gets to do things exactly the same between chapters. Doing so, trying to put every little detail into rules or into a standard is the opposite of what we want since it makes it that much harder for new organizers to start a ScalaBridge chapter.

ScalaBridge London, for example, has organized workshops that are advanced Scala. They are far from introductory and even with almost 2 years of professional Scala experience, I'm sure I could learn some new things from those workshops. Is that a problem? Of course not, it says nowhere that ScalaBridges aren't allowed to do advanced workshops. As long as they Goal and CoC in mind for the overall chapter organisation.

Similarly, we shouldn't write down if workshops should be a single session or a dozen, or what exactly a workshop should look like. It's much better to share what we've done before and let new organizers, mentors and students take from that whatever they want to use. And, it also means we shouldn't try to make rules about chapter names. And having an argument between chapters about what it "should" be is very non-conducive to what we're trying to do here.

If @adelbertc and co-organizers feel Silicon Valley is the best name, they probably have a good reason for that, and instead of arguing about the name we should support each other and try to make the best, most diverse, most inclusive workshops ever. :heart: 

We chose Amsterdam, Adelbert chose Silicon Valley, both are absolutely fine. :+1:

**Comment by nmcb** [comment]
Argued from the other side of the line I couldn't have written that better myself, still, it is worth noting though, that diversity is intrinsically breeds separation of common traits and thus acts against inclusion. It always does, when acting in the small. This time it did to the inclusion of a shared naming scheme, thus breaking with global standardised names. I'm against the name for the reasons stated, but will defend Alberts right to choose it just like you all have.

**Comment by nmcb** [comment]
(As a closing side note for this working day: I'm not often on github issue tracker, but the comment section really does not contain emoji's sensitive enough to deal with issues of a sensitive nature).

**Comment by adelbertc** [comment]
@nmcb Thank you for your input, you definitely bring up some points to think about, particularly about the balance between precision of location vs. accessibility and the associations a name like "Silicon Valley" may have.

After some thinking we have decided to stick with ScalaBridge Silicon Valley, at least in the interim. We believe it is unambiguous enough to localize the region events will be held in (e.g. Sunnyvale, Palo Alto, Mountain View) while not being so unambiguous that we encompass too large a region. As a practical matter we also believe continuing to use "ScalaBridge San Francisco" suggests events will only be held in SF which is definitely not the case. "Bay Area" is certainly an option, but in this case we chose to go with "Silcion Valley" because many other Meetups seem to use the same vague-yet-precise-enough name. Philosophically, I think @GerretS phrased it beautifully 😄 

On a related note I was looking at prior Issues related to this and found https://github.com/railsbridge/bridge_troll/issues/323 which has some interesting discussion.

**Conclusion**: We will keep ScalaBridge Silicon Valley in the interim.

**Comment by nmcb** [comment]
Feels as a very balanced decision to me, happy to have had this dialogue.

**Comment by GerretS** [comment]
@adelbertc That other issue you found is interesting. When we were adding the event to the site, we had to make both a chapter (done via Github issue) and a region (through the website). This felt like unnecessary bureaucracy but seeing there was a large discussion about it I can understand how this came to be.

I guess it would feel less bureaucratic if chapter entities could be managed via the website but that's a whole other discussion entirely.

**Comment by xingyif** [comment]
@siruguri Please take a look. Thank you!

**Comment by siruguri** [comment]
thanks for bumping it up @xingyif - I added the chapter - can you create an event now?

**Comment by adelbertc** [comment]
Looks like it worked - thanks @siruguri !

<img width="758" alt="Screen Shot 2019-08-22 at 9 35 44 PM" src="https://user-images.githubusercontent.com/1332980/63567124-d5532000-c524-11e9-9e79-c517986d1d38.png">
